# Generated by Django 5.0 on 2023-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plane",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plane_name", models.CharField(max_length=100)),
                ("id_by_user", models.IntegerField()),
                (
                    "passenger_capacity",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (100, "100"),
                            (200, "200"),
                            (300, "300"),
                            (400, "400"),
                            (500, "500"),
                        ],
                        null=True,
                    ),
                ),
                ("cons_per_mnt", models.FloatField()),
                ("tot_cons_per_minute", models.FloatField()),
                ("max_flight_time", models.FloatField()),
                ("fuel_cap", models.IntegerField()),
                ("max_pass_consumption", models.FloatField()),
                ("created_date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
