# Generated by Django 5.0 on 2023-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kami_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plane",
            name="cons_per_mnt",
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name="plane",
            name="fuel_cap",
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="plane",
            name="max_flight_time",
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name="plane",
            name="max_pass_consumption",
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name="plane",
            name="tot_cons_per_minute",
            field=models.FloatField(editable=False),
        ),
    ]
